language: csharp
solution: MapGen.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore MapGen.sln
  
script:
  - xbuild /p:Configuration=Release MapGen.sln
  - nunit-console ./MapGen.Model.Tests/bin/Release/MapGen.Model.Tests.dll