language: csharp
solution: MapGen.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore MapGen.sln
  
script:   # the following commands are just examples, use whatever your build process requires
  - xbuild /p:Configuration=Debug MapGen.sln
  - nunit-console MapGen.Model.Tests/bin/Debug/MapGen.Model.Tests.dll