language: csharp
solution: MapGen.sln

install:
  - nuget restore MapGen.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Release MapGen.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MapGen.Model.Tests/bin/Release/MapGen.Model.Tests.dll