//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapGen.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapGen.View.ResourcesView", typeof(ResourcesView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 168|255|255.
        /// </summary>
        internal static string ColorDepth1 {
            get {
                return ResourceManager.GetString("ColorDepth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140|213|233.
        /// </summary>
        internal static string ColorDepth2 {
            get {
                return ResourceManager.GetString("ColorDepth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 126|192|222.
        /// </summary>
        internal static string ColorDepth3 {
            get {
                return ResourceManager.GetString("ColorDepth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98|149|200.
        /// </summary>
        internal static string ColorDepth4 {
            get {
                return ResourceManager.GetString("ColorDepth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84|128|190.
        /// </summary>
        internal static string ColorDepth5 {
            get {
                return ResourceManager.GetString("ColorDepth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57|86|168.
        /// </summary>
        internal static string ColorDepth6 {
            get {
                return ResourceManager.GetString("ColorDepth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29|43|146.
        /// </summary>
        internal static string ColorDepth7 {
            get {
                return ResourceManager.GetString("ColorDepth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|124.
        /// </summary>
        internal static string ColorDepth8 {
            get {
                return ResourceManager.GetString("ColorDepth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string CountDepthScale {
            get {
                return ResourceManager.GetString("CountDepthScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_window_headicon {
            get {
                object obj = ResourceManager.GetObject("main_window_headicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,5.
        /// </summary>
        internal static string MoveSpeed {
            get {
                return ResourceManager.GetString("MoveSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_maps_window_database {
            get {
                object obj = ResourceManager.GetObject("table_maps_window_database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_close {
            get {
                object obj = ResourceManager.GetObject("window_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_maximize {
            get {
                object obj = ResourceManager.GetObject("window_maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_minimize {
            get {
                object obj = ResourceManager.GetObject("window_minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_data_lock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_data_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_data_unlock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_data_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_grid_lock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_grid_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_grid_unlock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_grid_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_minus {
            get {
                object obj = ResourceManager.GetObject("window_opengl_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_plus {
            get {
                object obj = ResourceManager.GetObject("window_opengl_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_points_lock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_points_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_points_unlock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_points_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_stripsedge_lock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_stripsedge_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_opengl_stripsedge_unlock {
            get {
                object obj = ResourceManager.GetObject("window_opengl_stripsedge_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
